In [1]:
import sys

sys.path.append('../')

In [2]:
from src.tacogfn.data.pharmacophore import PharmacoDB
from src.scoring.scoring_module import AffinityPredictor

/home/tsa87/anaconda3/envs/tacogfn/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [11]:
HEAD_PATH = "../model_weights/crossdocked_dim_256.pth"
device = 'cpu'

In [12]:
from omegaconf import OmegaConf
from src.pharmaconet.network import build_model

checkpoint = torch.load(HEAD_PATH, map_location="cpu")
config = OmegaConf.create(checkpoint["config"])
model = build_model(config.MODEL.HEAD)
model.load_state_dict(checkpoint["model"])

<All keys matched successfully>

In [13]:
model

AffinityHead(
  (ligand_encoder): GraphEncoder(
    (node_layer): Embedding(10, 128)
    (edge_layer): Embedding(5, 128)
    (conv_list): ModuleList(
      (0): GINEConv(nn=Sequential(
        (0): Linear(128, 128, bias=True)
        (1): LeakyReLU(negative_slope=0.01)
      ))
      (1): GINEConv(nn=Sequential(
        (0): Linear(128, 128, bias=True)
        (1): LeakyReLU(negative_slope=0.01)
      ))
      (2): GINEConv(nn=Sequential(
        (0): Linear(128, 128, bias=True)
        (1): LeakyReLU(negative_slope=0.01)
      ))
      (3): GINEConv(nn=Sequential(
        (0): Linear(128, 128, bias=True)
        (1): LeakyReLU(negative_slope=0.01)
      ))
    )
    (readout_layer): Linear(in_features=256, out_features=256, bias=True)
    (readout_gate): Linear(in_features=256, out_features=256, bias=True)
    (head): Sequential(
      (0): Linear(in_features=128, out_features=256, bias=True)
      (1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    )
  )
  (token_mlp): Seq

In [5]:
import torch

features = torch.load('../dataset/affinity_prediction_pharmacophores/crossdocked_dim_256/1a0g_A_rec.pt', map_location=device)

In [31]:
torch.concat([torch.rand(2, 128), torch.stack([features['pocket_features']]*2)], dim=1).shape

torch.Size([2, 384])

torch.Size([2, 256])

In [6]:
smiles_list = ['c1ccccc1', 'C1CCCCC1', 'CCCCCC']

In [7]:
for smiles in smiles_list:
    score = predictor.scoring(features, smiles)
    print(score)

tensor([-4.6001])
tensor([-3.8804])
tensor([-3.7410])
