In [8]:
import sys

sys.path.append('../')

In [9]:
from src.tacogfn.data.pharmacophore import PharmacoDB
from src.scoring.scoring_module import AffinityPredictor

In [10]:
HEAD_PATH = "../model_weights/base_100_per_pocket.pth"
device = 'cpu'
predictor = AffinityPredictor(HEAD_PATH, device)

In [15]:
import torch

features = torch.load('../dataset/docking_pharmacophores/1a3y_B_rec.pt', map_location=device)

In [16]:
smiles_list = ['c1ccccc1', 'C1CCCCC1', 'CCCCCC']

In [19]:
for smiles in smiles_list:
    score = predictor.scoring(features, smiles)
    print(score)

tensor([-6.4179])
tensor([-6.1828])
tensor([-6.0608])
